#!/usr/bin/env python3
"""
Blueprint Import API - Import warp_auto blueprints into warp_phase1_6_bundle

This script bridges warp_auto (offline ETL) and warp_phase1_6_bundle (runtime automation)
by importing JSON blueprints generated by warp_auto into the phase1_6_test.db database.

Usage:
    python import_blueprint.py <blueprint_file.json>
    python import_blueprint.py --all  # Import all blueprints from warp_auto
    python import_blueprint.py --list  # List available blueprints
"""

import json
import sqlite3
import sys
import os
from pathlib import Path
from datetime import datetime

# Paths
SCRIPT_DIR = Path(__file__).parent.resolve()
BUNDLE_ROOT = SCRIPT_DIR.parent
DATABASE_PATH = BUNDLE_ROOT / "phase1_6_test.db"
# From warp_tauri/warp_phase1_6_bundle -> up to ReverseLab, then to warp_auto
REVERSELAB_ROOT = BUNDLE_ROOT.parent.parent.parent
WARP_AUTO_ROOT = REVERSELAB_ROOT / "warp_auto"
WARP_AUTO_BLUEPRINTS = WARP_AUTO_ROOT / "blueprints"

def connect_db():
    """Connect to phase1_6_test.db"""
    if not DATABASE_PATH.exists():
        print(f"❌ Database not found: {DATABASE_PATH}")
        sys.exit(1)
    
    return sqlite3.connect(str(DATABASE_PATH))

def list_blueprints():
    """List all available blueprints from warp_auto"""
    if not WARP_AUTO_BLUEPRINTS.exists():
        print(f"❌ warp_auto blueprints directory not found: {WARP_AUTO_BLUEPRINTS}")
        return []
    
    blueprints = list(WARP_AUTO_BLUEPRINTS.glob("*.json"))
    
    print(f"\n📁 Available Blueprints ({len(blueprints)}):")
    print("=" * 60)
    
    for bp_path in blueprints:
        try:
            with open(bp_path) as f:
                data = json.load(f)
                workflow_id = data.get("workflow_id", "unknown")
                steps = len(data.get("steps", []))
                print(f"  - {bp_path.name}")
                print(f"      ID: {workflow_id}")
                print(f"      Steps: {steps}")
                print()
        except Exception as e:
            print(f"  - {bp_path.name} (error reading: {e})")
    
    return blueprints

def validate_blueprint(blueprint_data):
    """Validate blueprint schema"""
    required_fields = ["workflow_id", "steps"]
    
    for field in required_fields:
        if field not in blueprint_data:
            return False, f"Missing required field: {field}"
    
    if not isinstance(blueprint_data["steps"], list):
        return False, "steps must be a list"
    
    if len(blueprint_data["steps"]) == 0:
        return False, "steps cannot be empty"
    
    # Validate each step
    for i, step in enumerate(blueprint_data["steps"]):
        if "command" not in step:
            return False, f"Step {i} missing 'command' field"
    
    return True, "Valid"

def import_blueprint(blueprint_path, conn=None):
    """Import a single blueprint into phase1_6_test.db"""
    close_conn = False
    if conn is None:
        conn = connect_db()
        close_conn = True
    
    try:
        # Read blueprint
        with open(blueprint_path) as f:
            blueprint_data = json.load(f)
        
        # Validate
        valid, message = validate_blueprint(blueprint_data)
        if not valid:
            print(f"❌ Invalid blueprint: {message}")
            return False
        
        # Extract fields
        workflow_id = blueprint_data["workflow_id"]
        steps = blueprint_data["steps"]
        safety_score = blueprint_data.get("safety_score", 0.5)
        requires_approval = blueprint_data.get("requires_approval", True)
        auto_approve = not requires_approval
        
        # Convert to database format
        blueprint_json = json.dumps(blueprint_data)
        
        # Check if already exists
        cursor = conn.cursor()
        cursor.execute("SELECT id FROM plans WHERE name = ?", (workflow_id,))
        existing = cursor.fetchone()
        
        if existing:
            # Update existing
            plan_id = existing[0]
            cursor.execute("""
                UPDATE plans
                SET blueprint_json = ?,
                    safety_score = ?,
                    auto_approve = ?,
                    updated_at = ?
                WHERE id = ?
            """, (blueprint_json, safety_score, auto_approve, datetime.now().isoformat(), plan_id))
            
            conn.commit()
            print(f"✅ Updated existing plan: {workflow_id} (ID: {plan_id})")
        else:
            # Insert new
            cursor.execute("""
                INSERT INTO plans (name, blueprint_json, safety_score, auto_approve, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?)
            """, (workflow_id, blueprint_json, safety_score, auto_approve,
                  datetime.now().isoformat(), datetime.now().isoformat()))
            
            plan_id = cursor.lastrowid
            conn.commit()
            print(f"✅ Imported new plan: {workflow_id} (ID: {plan_id})")
        
        # Print summary
        print(f"   Steps: {len(steps)}")
        print(f"   Safety Score: {safety_score:.2f}")
        print(f"   Auto-approve: {auto_approve}")
        
        return True
    
    except Exception as e:
        print(f"❌ Error importing blueprint: {e}")
        return False
    
    finally:
        if close_conn:
            conn.close()

def import_all():
    """Import all blueprints from warp_auto"""
    blueprints = list_blueprints()
    
    if not blueprints:
        print("No blueprints found to import.")
        return
    
    print(f"\n🔄 Importing {len(blueprints)} blueprints...")
    print("=" * 60)
    
    conn = connect_db()
    success_count = 0
    
    for bp_path in blueprints:
        print(f"\nImporting: {bp_path.name}")
        if import_blueprint(bp_path, conn):
            success_count += 1
    
    conn.close()
    
    print(f"\n✅ Import complete: {success_count}/{len(blueprints)} successful")

def show_imported_plans():
    """Show all plans in database"""
    conn = connect_db()
    cursor = conn.cursor()
    
    cursor.execute("SELECT id, name, safety_score, auto_approve, created_at FROM plans ORDER BY id")
    plans = cursor.fetchall()
    
    conn.close()
    
    print(f"\n📊 Imported Plans ({len(plans)}):")
    print("=" * 60)
    
    if not plans:
        print("  No plans found in database.")
        return
    
    for plan_id, name, safety_score, auto_approve, created_at in plans:
        print(f"  ID {plan_id}: {name}")
        print(f"      Safety: {safety_score:.2f} | Auto-approve: {bool(auto_approve)} | Created: {created_at}")
        print()

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    arg = sys.argv[1]
    
    if arg == "--list":
        list_blueprints()
    
    elif arg == "--all":
        import_all()
    
    elif arg == "--show":
        show_imported_plans()
    
    elif arg == "--help":
        print(__doc__)
    
    else:
        # Import specific file
        blueprint_path = Path(arg)
        
        if not blueprint_path.exists():
            # Try relative to warp_auto/blueprints/
            blueprint_path = WARP_AUTO_BLUEPRINTS / arg
        
        if not blueprint_path.exists():
            print(f"❌ Blueprint file not found: {arg}")
            sys.exit(1)
        
        print(f"📥 Importing blueprint: {blueprint_path.name}")
        print("=" * 60)
        
        if import_blueprint(blueprint_path):
            print(f"\n✅ Successfully imported: {blueprint_path.name}")
        else:
            print(f"\n❌ Failed to import: {blueprint_path.name}")
            sys.exit(1)

if __name__ == "__main__":
    main()
